export const COUNTRY_CODES = [
  { code: '+91', country: 'IN', flag: '🇮🇳', name: 'India (+91)' },
  { code: '+1', country: 'US', flag: '🇺🇸', name: 'USA (+1)' },
  { code: '+44', country: 'GB', flag: '🇬🇧', name: 'UK (+44)' },
  { code: '+971', country: 'AE', flag: '🇦🇪', name: 'UAE (+971)' },
  { code: '+65', country: 'SG', flag: '🇸🇬', name: 'Singapore (+65)' },
  { code: '+61', country: 'AU', flag: '🇦🇺', name: 'Australia (+61)' },
  { code: '+49', country: 'DE', flag: '🇩🇪', name: 'Germany (+49)' },
  { code: '+33', country: 'FR', flag: '🇫🇷', name: 'France (+33)' },
  { code: '+81', country: 'JP', flag: '🇯🇵', name: 'Japan (+81)' },
  { code: '+86', country: 'CN', flag: '🇨🇳', name: 'China (+86)' },
  { code: '+880', country: 'BD', flag: '🇧🇩', name: 'Bangladesh (+880)' },
  { code: '+977', country: 'NP', flag: '🇳🇵', name: 'Nepal (+977)' },
  { code: '+92', country: 'PK', flag: '🇵🇰', name: 'Pakistan (+92)' },
  { code: '+94', country: 'LK', flag: '🇱🇰', name: 'Sri Lanka (+94)' },
  { code: '+966', country: 'SA', flag: '🇸🇦', name: 'Saudi Arabia (+966)' },
  { code: '+968', country: 'OM', flag: '🇴🇲', name: 'Oman (+968)' },
  { code: '+974', country: 'QA', flag: '🇶🇦', name: 'Qatar (+974)' },
  { code: '+965', country: 'KW', flag: '🇰🇼', name: 'Kuwait (+965)' },
  { code: '+973', country: 'BH', flag: '🇧🇭', name: 'Bahrain (+973)' },
  { code: '+60', country: 'MY', flag: '🇲🇾', name: 'Malaysia (+60)' },
  { code: '+62', country: 'ID', flag: '🇮🇩', name: 'Indonesia (+62)' },
  { code: '+63', country: 'PH', flag: '🇵🇭', name: 'Philippines (+63)' },
  { code: '+66', country: 'TH', flag: '🇹🇭', name: 'Thailand (+66)' },
  { code: '+84', country: 'VN', flag: '🇻🇳', name: 'Vietnam (+84)' },
  { code: '+27', country: 'ZA', flag: '🇿🇦', name: 'South Africa (+27)' },
  { code: '+254', country: 'KE', flag: '🇰🇪', name: 'Kenya (+254)' },
  { code: '+234', country: 'NG', flag: '🇳🇬', name: 'Nigeria (+234)' },
  { code: '+20', country: 'EG', flag: '🇪🇬', name: 'Egypt (+20)' },
  { code: '+55', country: 'BR', flag: '🇧🇷', name: 'Brazil (+55)' },
  { code: '+52', country: 'MX', flag: '🇲🇽', name: 'Mexico (+52)' },
  { code: '+7', country: 'RU', flag: '🇷🇺', name: 'Russia (+7)' },
  { code: '+39', country: 'IT', flag: '🇮🇹', name: 'Italy (+39)' },
  { code: '+34', country: 'ES', flag: '🇪🇸', name: 'Spain (+34)' },
  { code: '+31', country: 'NL', flag: '🇳🇱', name: 'Netherlands (+31)' },
  { code: '+41', country: 'CH', flag: '🇨🇭', name: 'Switzerland (+41)' },
  { code: '+46', country: 'SE', flag: '🇸🇪', name: 'Sweden (+46)' },
  { code: '+64', country: 'NZ', flag: '🇳🇿', name: 'New Zealand (+64)' },
];
